runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20"

automatic_scaling:
  cool_down_period: 120s
  min_num_instances: 1
  max_num_instances: 20
  cpu_utilization:
    target_utilization: 0.5

network:
  session_affinity: true
