declare namespace pins {
  //% fixedInstance shim=pxt::getPin(PIN_LED)
  const LED: PwmOnlyPin;

  //% fixedInstance shim=pxt::getPin(PIN_P0)
  const GP0: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P1)
  const GP1: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P2)
  const GP2: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P3)
  const GP3: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P4)
  const GP4: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P5)
  const GP5: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P6)
  const GP6: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P7)
  const GP7: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P8)
  const GP8: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P9)
  const GP9: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P10)
  const GP10: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P11)
  const GP11: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P12)
  const GP12: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P13)
  const GP13: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P14)
  const GP14: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P15)
  const GP15: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P16)
  const GP16: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P17)
  const GP17: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P18)
  const GP18: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P19)
  const GP19: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P20)
  const GP20: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P21)
  const GP21: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P22)
  const GP22: PwmPin;
  //% fixedInstance shim=pxt::getPin(PIN_P26)
  const GP26: AnalogInPin;
  //% fixedInstance shim=pxt::getPin(PIN_P27)
  const GP27: AnalogInPin;
  //% fixedInstance shim=pxt::getPin(PIN_P28)
  const GP28: AnalogInPin;
}
